---
# handlers file for elk

- name: Restart elasticsearch
  ansible.builtin.service:
    name: elasticsearch
    state: restarted
    enabled: true

- name: Restart logstash
  ansible.builtin.service:
    name: logstash
    state: restarted
    enabled: true

- name: Restart kibana
  ansible.builtin.service:
    name: kibana
    state: restarted
    enabled: true

- name: Restart filebeat
  ansible.builtin.service:
    name: filebeat
    state: restarted
    enabled: true
