---
# handlers file for webserver

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    enabled: true
    state: restarted

- name: Restart php-fpm
  ansible.builtin.service:
    name: php-fpm
    enabled: true
    state: restarted

- name: Restore mark
  ansible.builtin.file:
    path: /var/gfs-point/www/restore.run
    state: touch
    owner: nginx
    group: nginx
