---
- name: Copy secure-mysql shell script
  ansible.builtin.copy:
    src: secure-mysql.sh
    dest: /home/vagrant
    owner: root
    group: root
    mode: '0700'

- name: Install MySQL
  ansible.builtin.dnf:
    name:
      - mariadb-server
      - qpress
      - python3-PyMySQL
    state: present

- name: Configure mysqld
  ansible.builtin.template:
    src: mariadb-server.cnf.j2
    dest: /etc/my.cnf.d/mariadb-server.cnf
    owner: root
    group: root
    mode: '0644'
  register: mysql_configured

- name: Restart mysqld
  ansible.builtin.service:
    name: mariadb
    enabled: true
    state: restarted
  when: mysql_configured.changed

- name: Change password
  ansible.builtin.shell: "/home/vagrant/secure-mysql.sh {{ mysql_root_password }}"
  when: mysql_configured.changed

#- name: Flush handlers
#  ansible.builtin.meta: flush_handlers
