---
# handlers file for monitoring

- name: Start prometheus
  ansible.builtin.service:
    name: prometheus
    enabled: true
    state: restarted

- name: Start alertmanager
  ansible.builtin.service:
    name: prometheus-alertmanager
    enabled: true
    state: restarted

- name: Stop grafana
  ansible.builtin.service:
    name: grafana-server
    state: stopped

- name: Extract grafana config
  ansible.builtin.unarchive:
    src: grafana.tgz
    dest: /

- name: Change owner grafana config
  ansible.builtin.file:
    path: /var/lib/grafana
    state: directory
    recurse: yes
    owner: grafana
    group: grafana

- name: Start grafana
  ansible.builtin.service:
    name: grafana-server
    enabled: true
    state: restarted

- name: Start prometheus node exporter
  ansible.builtin.service:
    name: node_exporter
    enabled: true
    state: restarted

- name: Start gluster-exporter
  ansible.builtin.service:
    name: gluster-exporter
    enabled: true
    state: restarted

- name: Start mysqld_exporter
  ansible.builtin.service:
    name: mysqld_exporter
    enabled: true
    state: restarted
